package com.baidu.smarthome.phone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private Long id;
    /** Not-null value. */
    private String cotent;
    private long peerid;
    private boolean peermsg;
    /** Not-null value. */
    private java.util.Date timestamp;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String cotent, long peerid, boolean peermsg, java.util.Date timestamp) {
        this.id = id;
        this.cotent = cotent;
        this.peerid = peerid;
        this.peermsg = peermsg;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCotent() {
        return cotent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCotent(String cotent) {
        this.cotent = cotent;
    }

    public long getPeerid() {
        return peerid;
    }

    public void setPeerid(long peerid) {
        this.peerid = peerid;
    }

    public boolean getPeermsg() {
        return peermsg;
    }

    public void setPeermsg(boolean peermsg) {
        this.peermsg = peermsg;
    }

    /** Not-null value. */
    public java.util.Date getTimestamp() {
        return timestamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

}
